use_frameworks!

target 'YDChannelSelector_Example' do
  pod 'YDChannelSelector', :path => '../'

  target 'YDChannelSelector_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name.include?("QapDistribution")
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
    end
  end
end
